allow-missing-formatter = true
excludes = [".direnv/**/*"]

[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.keep-sorted]
command = "keep-sorted"
includes = ["*"]

[formatter.mdformat]
command = "mdformat"
includes = ["*.md"]

[formatter.taplo-format]
command = "taplo"
includes = ["*.toml"]
options = ["format"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]
